apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-model-vault.fullname" . }}
  labels:
    {{- include "ai-model-vault.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.api.jwtSecret }}
  jwt-secret: {{ .Values.api.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
